language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: C+OxQRUF67aAlQqZxqMk+6AGWD3cTc1nvoIv0StbyREEmO58MyGVKMmeWABMgzO5eqUoNine9rnFRjF6HAfSn7rvVO7FGB2r97IQj+kaOYmHQqKps29mPSa7B4Xva0CduuFm+79bmwF6YK7zahmdllvYll2eMLJbFZGldlFIypJCO6TMkfxt0s3NSuRDuV/Et6NIUpplbFED6xOtN9oAmqWQk3/HkWzwSYHM+fhIlt8HzG+bpI2DHn4aHy2I1rBaPd8eqFqG+a7z+s83L8K8pfedhF3b49HwUzggIHlMmOrkNVatcH7pp0ZC+JGlxLuvF6vCVTeRDYtqzDPlLIzzpFjGULzl7aFy7YkZ4NT3/adVw4J8+bNfhE65ngJsoaSatw5PqrJeLHa13TVmmJtcnDOA6u0ib2gKan/1cdM4ShKhypD1nXYsUv7Rsdq1Duqx+YO87KtN6AtakjApx7/90qZEBzNXsuqq8hQtDs7mHsYbyHmembTEQlyaBdVh/skQpLkjBTJOJJyORbRwWwC3Gj7p4+VEp0U9fkG+v6HtscvLFzYAD8ZBQNniwy7Av78SQbyrrvDDDo+ZPj6QcO4vi2XZlXszgPyZu+wLQ/hPWx9nUdo767byrenT7ToIk+hI0VI/XiaJC/muMZh8rBu4zlJpzSswJUmM2SLP/igh13E=
  app: steam-battle-api
  on:
    repo: gilmoreg/steam-battle-api
